### ISSUE TITLE
Suggestion | Triggerbot & Increased Customization

### ISSUE THREAD

**Issue by alt2hack** [BleachDrinker420/BleachHack#124]
I've been using BleachHack for just a few days, and I already enjoy it. I also think that it could definitely benefit off of the (in my experience) untapped market of 1.12+ closet cheating. I would really like to see the introduction of Triggerbot, as well as further customization to keep yourself unbanned. A setting that temporarily disables a hack while holding something other than a weapon (so it's not blatant you're hacking), and a setting that temporarily disables a hack while your y level is increasing (so you can get criticals better) are two things I would love to see in the future. A delay for auto-totem would also be greatly appreciated.

**Comment by BleachDrinker420** [comment]
Added AutoTotem delay and Triggerbot
