### ISSUE TITLE
Server scraper

### ISSUE THREAD

**Issue by ItsYoungDaddy** [BleachDrinker420/BleachHack#128]
- Would be interesting to see if you could make the scraper scrape the entire web or make the 1792 pings an adjustable value

- optionally have the IPs logged to a txt file instead of having nearly 200+ servers at times in the multiplayer serverlist

**Comment by BleachDrinker420** [comment]
there can be ~4.2 billion ip ardesses, so scraping the entire web at 20 ips / second would take about 2000 days or like 6 years and 99.99% of them wouldn't work.
but i will see if i make it changable

**Comment by ItsYoungDaddy** [comment]
this is why i shill this client, epic shit

**Comment by BleachDrinker420** [comment]
https://www.youtube.com/watch?v=hoS0PM20KJk
:trollface:
