### ISSUE TITLE
[Suggestion] Add a Builders Visuals to the Freecam Module.

### ISSUE THREAD

**Issue by DefaultO** [BleachDrinker420/BleachHack#157]
**Describe the Enhancement**
Add low transparency Visuals to all blocks (distance ``<= 5``) that you can break while in freecam.
optional: do it with air / empty blocks too. to show where you can place blocks too.

I was building my perfect sphere using http://oranj.io/blog/VoxelSphereGenerator at my main outpost/base. When I had to replace the outer part of the 2-4 thick cobble wall with glass. I used Freecam for that (which I usually use for such things, since what, not all know, is that you can place/break blocks close to your soulless body you left, even through walls) while being inside the sphere. You seem to be able to break/place till around ``~8`` blocks around you. But those might result in visible only blocks and are buggy. ``<= ~5`` should be fine.

This is a feature that would be handy to have, at least for me. But you are free to deny that one since others probably won't have so many benefits from it which means this got a pretty low priority. That's why I tried to implement it myself (and push a pull request which you could have declined/accepted then, it's basically free real estate).

Here's what I had so far:
_I edited the Freecam itself and added a SettingToggle to it with the label "Builders Mode". default: disabled_
```java
public Freecam() {
		super("Freecam", GLFW.GLFW_KEY_U, Category.PLAYER, "Its freecam, you know what it does",
				new SettingSlider("Speed", 0, 3, 0.5, 2),
				new SettingToggle("Horse Inv", true),
				new SettingToggle("Builders Mode", false)); // <-- This got added by me.
	}
```
_Then I added a simple check in the onEnable function/method/whatever to call that. And pasted code from the ChestESP class for the drawing, I kept it default, to see it drawing in-game first (just to see how it would look like), but nothing appeared._
```java
if (getSetting(2).asToggle().state) { // <-- I am not so sure about the index I did put here, but when I looked at the other classes, Sliders actually got an index too
			for (BlockEntity block : mc.world.blockEntities) {
				if (block.getPos().isWithinDistance(new Vec3i(playerPos[0], playerPos[1], playerPos[2]), 10)) {
					RenderUtils.drawFilledBox(block.getPos(), 0.5F, 0.2F, 1F, 0.7F);
				}
				else { continue; }
			}
		}
```
Tried it afterward by pasting that above into a
```java
@Subscribe
	public void onRender(EventWorldRender event){

	}
```
since that gets used by you for drawing stuff. No effect. Can you explain to me what I am doing wrong here? Probably how I get the player's position. But that should be not wrong since that's how arrays work or rather how you did pass the values to it, right?

**Screenshots**
_Orange + Red are the areas that are buggy. Everything inside blue is totally fine to build at. That's 2D for easier understanding, but of course, you have to think a sphere around you. There doesn't have to be any complex formulas for that. A check for the distance between player's pos and block's pos should be enough_

![image](https://user-images.githubusercontent.com/42414542/91796107-b00ced80-ec1f-11ea-95a1-dfe2b4cb23c4.png)

I can send you privately a vid of me actively using Freecam to build the sphere I mentioned above. It is unedited which why I rather avoid leaking my coords to the public. This Feature is rather for the Builders that use Bleach. And when having a look at the vid you will see how op it actually would be, if it just would be a thing.

**Comment by BleachDrinker420** [comment]
big pog, i'll add it later

**Comment by DefaultO** [comment]
You don't have to actually. It's a so old feature request. And I was so bad at Java back there that I couldn't even fork the project and add it myself. @BleachDrinker420

**Comment by BleachDrinker420** [comment]
ok
