### ISSUE TITLE
Unable to load game while bleachhack mod is in folder.

### ISSUE THREAD

**Issue by rainbow-glitch** [BleachDrinker420/BleachHack#164]
So every single time I try to launch Minecraft while the mod is in the folder it crashes.
After removing all the other mods and the problem still continuing I tried every single version[1.14.4,1.15.2,1.16.2](spent a lot of time installing the versions of fabric) and it still doesn't work.

It appears to be launching but a few seconds later it shows a crash report(https://hatebin.com/gfubwqyesj).

I have been trying for over 6 hours now. Tried compiling it myself aaannddddd didn't work.
I would really appreciate help.
 
Sorry bout bad grammar.

**Comment by TheAirBlow** [comment]
Caused by: java.lang.NullPointerException
	at bleach.hack.module.mods.Xray.onEnable(Xray.java:71)
	at bleach.hack.module.Module.setToggled(Module.java:131)
	at bleach.hack.utils.file.BleachFileHelper.readModules(BleachFileHelper.java:104)
	at bleach.hack.BleachHack.onInitialize(BleachHack.java:43)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)

It initializes the mod, read module states, enable module (XRay), and then the onEnable() function crashes the game.

**Comment by TheAirBlow** [comment]
mc.worldRenderer.reload();

This is waht causes the crash.
How it can reload worldRenderer, if it's null?

So when it tries to do this, it crashes.

I think we must use try { ... } catch { ... } for now.

**Comment by BleachDrinker420** [comment]
Fixed sometime ago

**Comment by yentdevries** [comment]
i have the same problem, how to fix this

**Comment by yentdevries** [comment]
> Fixed sometime ago

well whats the fix?
