### ISSUE TITLE
Xray with Sodium / complete instability with OptiFabric

### ISSUE THREAD

**Issue by degeneratehyperbola** [BleachDrinker420/BleachHack#171]
Xray simply doesn't work with Sodium, when it is on nothing changes but when you turn it off every block just becomes invisible.
With OptiFabric minecraft won't even launch.
Tried with 1.16.4 and 1.16.3.

**Comment by TheAirBlow** [comment]
logs please

**Comment by BleachDrinker420** [comment]
Optifine works completely fine if you remove the MixinBlockModelRenderer mixin, probably the same with sodium too

**Comment by Hey-Im-Jerry** [comment]
I have the exactly same issue where do I find it? "MixnBlockModelRenderer mixin".

**Comment by BleachDrinker420** [comment]
open the jar with winrar/zip, open the "bleachhack.mixins.json" file inside, remove the line that says MixnBlockModelRenderer and save

**Comment by degeneratehyperbola** [comment]
Removing "MixinBlockModelRenderer" left everything unchanged
Also removing "MixinWorldRenderer" did same

While having both of them removed, did not notice any graphical artifacts

### This is with no xray (notice ambient occlusion present):
![image](https://user-images.githubusercontent.com/65950527/111380748-6eb8c880-86ad-11eb-9c31-8b56cdda3d7f.png)

### This is first time turning xray on:
![image](https://user-images.githubusercontent.com/65950527/111380884-9d36a380-86ad-11eb-8dfa-89fe8e86b3b3.png)

### And this is after turning it off and all following toggles:
![image](https://user-images.githubusercontent.com/65950527/111381016-ce16d880-86ad-11eb-80ce-c6a268e6fc11.png)

**Comment by Hey-Im-Jerry** [comment]
Now Im able to launch minecraft with optifine, but still nothing change with Xray.

**Comment by BleachDrinker420** [comment]
Optifabric crash fixed, too lazy to fix sodium

**Comment by degeneratehyperbola** [comment]
bruh, sodium is my friend :(

**Comment by Cabbasca** [comment]
> Optifabric crash fixed, too lazy to fix sodium

fix sodium
