### ISSUE TITLE
Game won't create a window

### ISSUE THREAD

**Issue by janosBTW** [BleachDrinker420/BleachHack#182]
i launch 1.16 with latest bleachhack for this version and it does show up as a process but doesn't create a window and is open without any crash message.

OS: MacOS Catalina

**Comment by ikearefrigerator** [comment]
have you tried restarting the launcher?

**Comment by BleachDrinker420** [comment]
Check the "Open output log when minecraft starts" button in the launcher and see what comes up

**Comment by janosBTW** [comment]
> Check the "Open output log when minecraft starts" button in the launcher and see what comes up

Preparing to launch minecraft client for fabric-loader-0.11.2-1.16.5
14:12:20.596
Checking installations.
14:12:20.598
Minecraft client fabric-loader-0.11.2-1.16.5 is ready to start.
14:12:20.598
Starting!
14:12:20.679
Using default game log configuration client-1.12.xml (outputs XML)
14:12:27.940
Loading for game Minecraft 1.16.5
14:12:28.994
[FabricLoader] Loading 5 mods: minecraft@1.16.5, java@8, bleachhack@1.16.5, fabricloader@0.11.2, com_github_vatuu_discord-rpc@1.6.2
14:12:29.063
SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/Users/Szaniewski/Library/Application%20Support/minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
14:12:52.151
Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
14:12:59.423
Setting user: ItzJanosBTW
14:13:00.755
Backend library: LWJGL version 3.2.1 build 12

**Comment by BleachDrinker420** [comment]
oh yea pretty sure it doesn't work on mac, i'll look into it later

**Comment by BleachDrinker420** [comment]
use https://github.com/ChiquitaV2/MacHack/ instead

**Comment by BleachDrinker420** [comment]
fixed
