### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by SakizciAdam** [BleachDrinker420/BleachHack#189]
Every 1-2 seconds there is a lag spike, its really annoyying. It only happens in bleach hack.
Drops my fps to 0 from 300. Im not using any render hacks

GTX 1050 Ti 4gb
Amd ryzen 5 2400g

**Comment by BleachDrinker420** [comment]
after it happens, close minecraft, then send `.minecraft/logs/latest.log` here
