### ISSUE TITLE
i made pixel art for bleachhack idk where to put it

### ISSUE THREAD

**Issue by AcaiBerii** [BleachDrinker420/BleachHack#212]
[fanart](https://i.ibb.co/tmcLwNR/2021-04-13-20-15-02.png)
hope u enjoy i spent today years on it

**Comment by ottosakura** [comment]
wHERE IS PICTURE

**Comment by lasnikprogram** [comment]
https://i.ibb.co/tmcLwNR/2021-04-13-20-15-02.png

**Comment by ottosakura** [comment]
hard work
