### ISSUE TITLE
Suggestion: Nuker ESP

### ISSUE THREAD

**Issue by Godeps2891** [BleachDrinker420/BleachHack#215]
damn ok, enter submits the issue

just a box around you displaying the range of nuker

**Comment by BleachDrinker420** [comment]
Added in https://github.com/BleachDrinker420/BleachHack/commit/ff5ca0561e2943294b547af908546e9b3358a07f

**Comment by BleachDrinker420** [comment]
oh wait i though you meant esp around the blocks you're mining

**Comment by BleachDrinker420** [comment]
Added quantum nuker esp https://github.com/BleachDrinker420/BleachHack/commit/dcadc5dafdeee9ce4b8269a936c88921fe7b018d
