### ISSUE TITLE
Add Velocity

### ISSUE THREAD

**Issue by Drakesdrs** [BleachDrinker420/BleachHack#218]
## Velocity

Velocity prevents you from taking knockback from external enetities.

**Comment by BleachDrinker420** [comment]
b ruh

**Comment by BleachDrinker420** [comment]
![Untitled](https://user-images.githubusercontent.com/36450388/116790064-b0150400-aab2-11eb-9e14-834931c050fa.png)

**Comment by lasnikprogram** [comment]
Maybe you are trolling @Drakesdrs but if not (wtf???!)  . You should use the search feature in the click gui

**Comment by Drakesdrs** [comment]
ahhhh I did .toggle Velocity
