### ISSUE TITLE
Entitycontol enhancement

### ISSUE THREAD

**Issue by lasnikprogram** [BleachDrinker420/BleachHack#222]
Let it control strider and pig with saddle on them. Not completely sure if this is still possible but I remember cruising with my own entitycontrol through my world.

**Comment by ChiquitaV2** [comment]
It is possible 🙂

**Comment by BleachDrinker420** [comment]
added https://github.com/BleachDrinker420/BleachHack/commit/7dcfa356094da552cb32e403ecc822207f085457
