### ISSUE TITLE
[Suggestion] Maybe merge some features from epearl?

### ISSUE THREAD

**Issue by DarkReaper231** [BleachDrinker420/BleachHack#228]
I mean it has some really good stuff and also fixes few bugs that are still present in the original repo. You should consider merging at least some stuff you find useful.

**Comment by BleachDrinker420** [comment]
What are the bugs that are still in the original?

**Comment by DarkReaper231** [comment]
If I recall correctly. Notebot stealer doesn't save the files correctly. It sometimes doesn't saves them at all. I remember fixing this bug in epearl.
