### ISSUE TITLE
add a search window in the clickgui

### ISSUE THREAD

**Issue by xWackelpuddingx** [BleachDrinker420/BleachHack#232]
please

**Comment by BleachDrinker420** [comment]
![Untitled](https://user-images.githubusercontent.com/36450388/117487265-26aa7980-af6b-11eb-831b-b2384f74233b.png)
diarrhea sound effect

**Comment by xWackelpuddingx** [comment]
oh thank you lol

**Comment by xWackelpuddingx** [comment]
also this is probably just me being dumb again but only elytra control works (using the latest release)

**Comment by xWackelpuddingx** [comment]
nevermind i had to remove meteor client then it worked

**Comment by BleachDrinker420** [comment]
meteor velocity breaks everything for some reason, just use bh novelocity instead
