### ISSUE TITLE
Color picker oopsie

### ISSUE THREAD

**Issue by degeneratehyperbola** [BleachDrinker420/BleachHack#234]
### Colors display wrongly in ClickGUI color pickers:
![image](https://user-images.githubusercontent.com/65950527/118110019-92b53380-b3ea-11eb-9a71-2fd7c4ca7d01.png)

### Using this version
5fddf557cc7a688721048f6c01767a09acbda234

![image](https://user-images.githubusercontent.com/65950527/118110043-99dc4180-b3ea-11eb-9e12-9c2fcbdaa0e3.png)

**Comment by BleachDrinker420** [comment]
what os, java version and other mods are you using?

**Comment by degeneratehyperbola** [comment]
Windows Java 11
Other mods:
- Sodium
- WorldEdit
- WorldEdit CUI

**Comment by degeneratehyperbola** [comment]
Just tried without any other mod and same happens
![image](https://user-images.githubusercontent.com/65950527/118112520-ca71aa80-b3ed-11eb-8290-847b4a988364.png)

**Comment by BleachDrinker420** [comment]
how do you have that font?

**Comment by degeneratehyperbola** [comment]
That is a resource pack, it includes only the TTF font and nothing else. And I have noticed that without it everything works fine.
### Here are rasterization parameters for it:
![image](https://user-images.githubusercontent.com/65950527/118113200-a82c5c80-b3ee-11eb-8fae-227943207771.png)

**Comment by BleachDrinker420** [comment]
yea pretty sure i can't do anything about it then
