### ISSUE TITLE
Suggestion: ClickGui option to not render a gui tint for it

### ISSUE THREAD

**Issue by Godeps2891** [BleachDrinker420/BleachHack#238]
cringe gui tint
![image](https://user-images.githubusercontent.com/54289108/119172970-db15c680-ba66-11eb-9fc6-a79eb9c54703.png)

no gui tint
![image](https://user-images.githubusercontent.com/54289108/119172986-e0731100-ba66-11eb-8bc4-492c994a9ce0.png)

**Comment by BleachDrinker420** [comment]
inertia font wtf

**Comment by Godeps2891** [comment]
Cumfortaa

**Comment by BleachDrinker420** [comment]
Added in https://github.com/BleachDrinker420/BleachHack/commit/c3e783ebd06fc59ae4ec3b3f42c29d96d49d81c1
