### ISSUE TITLE
Inertia machine broke again

### ISSUE THREAD

**Issue by Godeps2891** [BleachDrinker420/BleachHack#239]

**Comment by Godeps2891** [comment]
game launches but can not connect to servers (i was stupid and pressed enter again when making the issue) https://paste.ee/p/fLFzl

**Comment by Godeps2891** [comment]
broke in the build that readded anti chunk ban https://github.com/BleachDrinker420/BleachHack/actions/runs/853843385

**Comment by BleachDrinker420** [comment]
https://github.com/BleachDrinker420/BleachHack/commit/1a0224e6c41f7c8e4e24bc69f4ab5c473c9dd86e
