### ISSUE TITLE
Istackdupe broken if you have fabric api in youre mods folder

### ISSUE THREAD

**Issue by PandaKingJnr** [BleachDrinker420/BleachHack#240]
i dont know why but you need to fix it

**Comment by BleachDrinker420** [comment]
pretty sure its just broken

**Comment by PandaKingJnr** [comment]
nah it works when you take fabric api out
pls fix so if any client needs fabric api i can use

**Comment by business-goose** [comment]
wat mods u have installed

**Comment by PandaKingJnr** [comment]
i have meteor too, i took that out and it still didnt work so i put it back in

**Comment by RazorShard** [comment]
Same problem will u ever fix it and for the time being could u tell me another mod for the donkey dupe?

**Comment by RazorShard** [comment]
creepy salhack works but its forge so ye

**Comment by BleachDrinker420** [comment]
removed istackdupe, irrelevant now
