### ISSUE TITLE
You can't see nametags through banners.

### ISSUE THREAD

**Issue by dingboy99** [BleachDrinker420/BleachHack#243]
![2021-05-29_09 17 20](https://user-images.githubusercontent.com/84995877/120043620-65aa8700-c060-11eb-8bc5-acc31dfe3ed9.png)
this is 1.16.5 btw

**Comment by BleachDrinker420** [comment]
Fixed in https://github.com/BleachDrinker420/BleachHack/commit/9333e3d9cf8ee2c057b5130da73e2f26c034979d
