### ISSUE TITLE
Feature Request: Liquid/Fluid Killer

### ISSUE THREAD

**Issue by DefaultO** [BleachDrinker420/BleachHack#245]
### Liquid/Fluid Killer, name it whatever you want
What this feature should do is place blocks at lava/water sources. Helpful for creating parameters at your base. As you don't have to worry about falling into lava when nuking the whole area. This feature can not only be used for creating parameters but tunneling in the nether too. Another thing I love to do.

As of now, I have to **Freecam** and build a wall outside my tunnel to prevent the lava from coming near. Such a feature would help me immensely and speed up the process of creating a parameter and tunneling in the nether. Haven't found a single hack client doing that __yet__.

**Comment by BleachDrinker420** [comment]
bru
there is already liquid filler

**Comment by DefaultO** [comment]
Oh lol. That's new.
