### ISSUE TITLE
My game crashes whenever i click on a crafting table

### ISSUE THREAD

**Issue by h4il0** [BleachDrinker420/BleachHack#249]
The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

this is the error

**Comment by BleachDrinker420** [comment]
Should be fixed in https://github.com/BleachDrinker420/BleachHack/commit/96e57fd73f4bbd0eb58f17af08ab182b5f4b58ae
