### ISSUE TITLE
Suggestion: Packet Sneak

### ISSUE THREAD

**Issue by Psychogenic88** [BleachDrinker420/BleachHack#254]
This is useful for those of us that still use this mod for griefing.

Rather then setting sneak to toggle, holding down your sneak key/actually sneaking, packet sneak allows you to move normally but only appear as if you're sneaking to other players.

This is the only addition to the client that I _personally_ would need in order to consider this one of the few clients I regularly use.

**Comment by BleachDrinker420** [comment]
https://github.com/BleachDrinker420/BleachHack/commit/f55b65a39c2d73b9062c44bd5e4efe88e2f4e1c8
