### ISSUE TITLE
[Suggestion] add more block in surround

### ISSUE THREAD

**Issue by LDoom** [BleachDrinker420/BleachHack#261]
A major missing block is the Respawn Anchor.

![image](https://user-images.githubusercontent.com/73355762/123808143-1ac99c80-d8b6-11eb-8b03-6eefbbf19334.png)

anchor does not affect the face place in the nether.

**Comment by BleachDrinker420** [comment]
Added in https://github.com/BleachDrinker420/BleachHack/commit/9856741bbdf66da5dbcdd4a71471793e27350187
