### ISSUE TITLE
Xray suggestion

### ISSUE THREAD

**Issue by ShapeX1** [BleachDrinker420/BleachHack#266]
It would be a nice addition if you could add the wet and dry sponge to the xray

**Comment by BleachDrinker420** [comment]
heres a secret

YOU CAN EDIT XRAY BLOCKS
![output-onlinegiftools](https://user-images.githubusercontent.com/36450388/125175061-fa5ce480-e1c9-11eb-83de-a10f5d7db1b9.gif)
S

**Comment by BleachDrinker420** [comment]
![Untitled](https://user-images.githubusercontent.com/36450388/125175111-2a0bec80-e1ca-11eb-8df1-0607b633b74c.png)
