### ISSUE TITLE
Very undetailed descriptions 

### ISSUE THREAD

**Issue by SenseiWu25** [BleachDrinker420/BleachHack#270]
Many modules and commands have very unspecific or joke descriptions when you hover over them or do $help

**Comment by BleachDrinker420** [comment]
Write me some new descriptions then

**Comment by BleachDrinker420** [comment]
Kinda fixed in https://github.com/BleachDrinker420/BleachHack/commit/07b02d955e04ea689f64497e7e5653bb65b10bce, reopen if you wanna write new descriptions for me
