### ISSUE TITLE
[Bug] Notebot says there are missing blocks even tho there aren't

### ISSUE THREAD

**Issue by DarkReaper231** [BleachDrinker420/BleachHack#273]
I am trying to play Senorita. It is on 5th page of notebot gui. It says there are 5402 notes missing but they are all there. And the music is off. It doesn't click some notes for some reason.

**Comment by DarkReaper231** [comment]
I think the GUI displays the notes wrong. Like for example on Senorita it says it needs 13 blocks of wool but it uses 20 when I use it. I think it displays wrong requirements.

**Comment by BleachDrinker420** [comment]
Fixed in https://github.com/BleachDrinker420/BleachHack/commit/45cef78650002441703d8c44ef7ab3012bffacbb.
not really sure why the gui and real blocks don't match

**Comment by DarkReaper231** [comment]
Works perfectly now!!
