### ISSUE TITLE
[Suggestion] coords specification for $nbt command 

### ISSUE THREAD

**Issue by DarkReaper231** [BleachDrinker420/BleachHack#279]
Would be nice to be able to specify coords of block or entity around you so you don't have to just hold the thing in your hand or ride on it but also just getting nbt from stuff standing around you.

**Comment by BleachDrinker420** [comment]
Added in https://github.com/BleachDrinker420/BleachHack/commit/f9230cb368125cc221ada697756ac362a148b94f

**Comment by DarkReaper231** [comment]
Man you're a beast!

**Comment by DarkReaper231** [comment]
Bro Bleach might not have thousands of features but it has the coolest features. Few of them like this one are even useful for server admin like me. Also your code is sooo clean and beginner friendly 11/10
