### ISSUE TITLE
[Suggestion] Custom UI, Legit scaffold, speedrun and more

### ISSUE THREAD

**Issue by KitCatzYeet** [BleachDrinker420/BleachHack#289]
Add custom UI where you can move your hotbar, health, hunger, pvp bar thing all around your screen for some reason. Add more ‘fun’ ‘utilities’ like LSD hack on Wurst or random sneak where you sneak randomly, this could be fun as challenges for super-sweats. Add speed bridge ‘help’, like a more legit version of scaffold. Add baritone. Add auto-speedrun or auto find structures.

**Comment by BleachDrinker420** [comment]
please split your suggestions

**Comment by KitCatzYeet** [comment]
Ok, it just take sooo long.
