### ISSUE TITLE
Auto speedrun

### ISSUE THREAD

**Issue by KitCatzYeet** [BleachDrinker420/BleachHack#294]
Does the speed run FOR YOU!

**Comment by DarkReaper231** [comment]
You mean tool assisted speedrun? If so just do that on set seed with autohotkey or something. If you mean random seed, that"s pretty hard to do. It would involve artificial intelligence and I'm afraid we aren't there yet. Unless you want to try make bot that will have a lot of if else statements using Baritone but I doubt anybody will attempt anything like that any time soon.

**Comment by BleachDrinker420** [comment]
weird utility but ok
