### ISSUE TITLE
Nuker cannot target some ocean block types

### ISSUE THREAD

**Issue by Entropycrafter** [BleachDrinker420/BleachHack#303]
BleachHack 1.1 nuker is unable to target these blocks
 *_coral_fan
 *_coral
 *_coral_wall_fan
sea_pickle
seagrass
tall_seagrass
kelp_plant

There does not seem to be any issue with targeting dead coral such as dead_horn_coral_fan

**Comment by BleachDrinker420** [comment]
Fixed in https://github.com/BleachDrinker420/BleachHack/commit/958870c912d978d52e2eadf33bedfd9dfb163f0a
