### ISSUE TITLE
[Bug] logout spots won't go away

### ISSUE THREAD

**Issue by Sandwich4780** [BleachDrinker420/BleachHack#306]
logout spots won't disappear after the person logs back in, and combat modules will attack the logout spot.

**Comment by BleachDrinker420** [comment]
logout spot do disappear when they log in?? can you send a video/screenshot?

**Comment by BleachDrinker420** [comment]
nvm they don't
1/2 fixed https://github.com/BleachDrinker420/BleachHack/commit/44e5ef76b1f4f238bfc090532d94d57847b2e0be

**Comment by BleachDrinker420** [comment]
2/2 fixed https://github.com/BleachDrinker420/BleachHack/commit/f96eb75c45a7357270edb32be80da86000f3d9c5
