### ISSUE TITLE
[Bug] BetterChat decryptor still doesn't work on certain chat plugins

### ISSUE THREAD

**Issue by SolsticeSpectrum** [BleachDrinker420/BleachHack#307]
![OnPaste 20210811-182121](https://user-images.githubusercontent.com/38611351/129066271-0ee9fd1f-01bc-47d1-936e-e1de30413d5c.png)

When I type into chat directly, it works but using /msg makes the decryptor not work in this plugin. Btw /register finally works so good work on that one.

I don't know the name of that plugin but the message is formatted like this behind the curtain
```
§6§l(§e§l!§6§l) §e§lTy §6-> §e§lmacs §aMESSAGE
```

**Comment by DarkReaper231** [comment]
Btw if you wanna try it out, the use the plugin here play.dream-land.cz
