### ISSUE TITLE
[Suggestion] Add module that will display how many bees are in hive or farm and different status on other blocks

### ISSUE THREAD

**Issue by DarkReaper231** [BleachDrinker420/BleachHack#308]
So since BleachHack is kinda a client for not only cheats but also very useful utilities, I thought that it could have something to display status of of some blocks and entities. I can't really think about other ideas now but I came up with this idea when I made a bee farm but I didn't have any way to tell how many bees I have so that is one thing this module or command could do. Other stuff could be displaying babies age maybe or something like that? Idk would be nice to come up with other stuff so this module can do more than just display how many bees are in beehive. I'm gonna think about it for little bit longer and when I come up with other stuff it could do, I'll comment it.

**Comment by BleachDrinker420** [comment]
the bottom right text in the f3 menu shows exactly that

**Comment by DarkReaper231** [comment]
honey level means number of bees?

**Comment by DarkReaper231** [comment]
No f3 doesn't show number of bees inside a nest

**Comment by DarkReaper231** [comment]
Only /data command can tell this information and thinking about this, minecraft server might not even show you this info unless you have permissions and can do /data command.
