### ISSUE TITLE
[Bug] Server reconnect button will make you join a random server from your server list

### ISSUE THREAD

**Issue by iCrazeiOS** [BleachDrinker420/BleachHack#312]
Not sure if it also happens when the reconnect screen is triggered by another method, but if the server is down and you try to connect, you will instead be connected to a random server in your server list.

Video demo: https://streamable.com/lmf5q6

**Comment by BleachDrinker420** [comment]
Fixed https://github.com/BleachDrinker420/BleachHack/commit/63055060ae4d602d830ef1eb8db10ebde1f65276
