### ISSUE TITLE
Autoeat 

### ISSUE THREAD

**Issue by dudethis** [BleachDrinker420/BleachHack#320]
I suggest that you put an autoeat like in wurst client because its very helpful for xp farms that chew through your food bar

**Comment by dudethis** [comment]
also sorry i didnt know how to put labels

**Comment by orsondmc** [comment]
If this works with no slow I'd be super happy

**Comment by BleachDrinker420** [comment]
Added in https://github.com/BleachDrinker420/BleachHack/commit/106d9eb13329a1013f27988df90596397b26fea1
