### ISSUE TITLE
Suggestion: spoof fabric client as vanilla

### ISSUE THREAD

**Issue by Teryllim** [BleachDrinker420/BleachHack#356]
When you connect to a minecraft server with any version of fabric, the server can see that the client is using the fabric mod loader. It would be nice if there was a button or switch in the settings that allowed the user to enable a feature that spoofed the fabric 1.17.1 client to look like a vanilla 1.17.1 client.

**Comment by BleachDrinker420** [comment]
Added in https://github.com/BleachDrinker420/BleachHack/commit/3ff5020fea07700cac1d5ec73400f5876cefe162
