### ISSUE TITLE
[Suggestion] Add Google Voice Input 

### ISSUE THREAD

**Issue by DarkReaper231** [BleachDrinker420/BleachHack#374]
I got very interesting idea. I got lazy and thought that I don't want to type into chat so I was thinking about Google Voice Input which is pretty good and support almost all languages these days.

This module could use the Google API for voice input. You could edit what language you wanna use. And you could enter text this way to all input boxes and chat.

**Comment by BleachDrinker420** [comment]
worse than the lovense vibrator integration
