### ISSUE TITLE
[Suggestion] Remote Control

### ISSUE THREAD

**Issue by DarkReaper231** [BleachDrinker420/BleachHack#384]
This module would allow client to be controlled by anybody in the server. Would be nice if it even had friends support so you can only allow it for certain people. Someone could then send you pm, msg, whisper and so on with a command like .remote $toggle killaura or something between those lines. I think it could be handy when you have baritone or something.

**Comment by BleachDrinker420** [comment]
self rat module

**Comment by DarkReaper231** [comment]
Well maybe but I have plenty of interesting use cases for it. You see Kami had it but it's dead so I wish there was alternative and you make cool modules often so I thought this could be it.
