### ISSUE TITLE
[Bug] Crash moment

### ISSUE THREAD

**Issue by RedCarlos26** [BleachDrinker420/BleachHack#393]
Idk I just crash when I take damage
[crash-2021-12-03_20.46.58-client.txt](https://github.com/BleachDrinker420/BleachHack/files/7653123/crash-2021-12-03_20.46.58-client.txt)

**Comment by BleachDev** [comment]
Fixed in https://github.com/BleachDrinker420/BleachHack/commit/e1a6478555a0c8f7525c0bbbe2518d166e25b517
