### ISSUE TITLE
[bug] resetting configs

### ISSUE THREAD

**Issue by 1drw** [BleachDrinker420/BleachHack#394]
at random i'll log in and my config will be reset, ui reset and no binds
theres no real pattern to it that ive noticed its only been an issue with 1.2.2 and onwards

**Comment by Blurxxy** [comment]
Yeah I had the same issue

**Comment by stfu23489** [comment]
Can relate

**Comment by BleachDev** [comment]
Fixed in https://github.com/BleachDrinker420/BleachHack/commit/5faa1f30553e57a0a7f76bd83e31a2e5e7a878a6
