### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by Seepy69** [BleachDrinker420/BleachHack#398]
when using the normal optifne instead of pre version it crashes and when i use pre version i cant see anything unsure this is just me but i think its a bug

**Comment by OBNinjaa** [comment]
> when using the normal optifne instead of pre version it crashes and when i use pre version i cant see anything unsure this is just me but i think its a bug

Yeah i have the same issue.

**Comment by beebo1** [comment]
Yeah, same here, and it's definitely an issue with bleachhack and Optifabric together.

**Comment by BleachDev** [comment]
Fixed some time ago
