### ISSUE TITLE
flush now / game crashing issue

### ISSUE THREAD

**Issue by Blurxxy** [BleachDrinker420/BleachHack#399]
everytime I try updating the client it crashes or sometimes when I even try opening it, it crashes.
When It crashes this peice of code pops up. The only way I figured this the client would work would be using Tlauncher or kjust uninstall and reinstall fabric loader. Please fix this was not like this before and its been happening ever since the update
Code: 
[Launcher] Minecraft closed with exit code: 1
[Launcher] Launcher exited.
flush now
flush now

**Comment by BleachDev** [comment]
We don't support tlauncher
