### ISSUE TITLE
flushing issue / explained better.

### ISSUE THREAD

**Issue by Blurxxy** [BleachDrinker420/BleachHack#400]
When I used **_Minecraft Launcher_** BleachHack would crash and it would pull up some sort of code saying flush now. I switched to Tlauncher and It worked fine then It just started crashing over again.
I use BleachHack & Meteor Client together so I thought it was a problem with Meteor and when I removed meteor it still kept crashing and I just used Meteor and It worked perfectly fine. The only way I got BleachHack to work was installing Fabric Loader over again and If I closed Minecraft I would have to reinstall Fabric loader again.

**Comment by BleachDev** [comment]
Send everything it says
