### ISSUE TITLE
DiscordRPC only working in releases

### ISSUE THREAD

**Issue by xWackelpuddingx** [BleachDrinker420/BleachHack#414]
![2022-01-16_20 30 25](https://user-images.githubusercontent.com/73304500/149674987-ee68735e-a165-4523-a5b4-18f15a7046ab.png)
works on releases but not if you download the code (1.17.1)

**Comment by BleachDev** [comment]
Pretty sure it happens because i switched the rpc library recently but send latest.log after discordrpc disappears so i can see what happened

**Comment by xWackelpuddingx** [comment]
[latest.log](https://github.com/BleachDrinker420/BleachHack/files/7877786/latest.log)

**Comment by BleachDev** [comment]
Fixed in https://github.com/BleachDrinker420/BleachHack/commit/0b4a2dffb0b8089fb18bb7cf4262d05c3e891eef
