### ISSUE TITLE
Xray Fix

### ISSUE THREAD

**Issue by 0Ariel0** [BleachDrinker420/BleachHack#437]
I was testing the hack and I realized that xray is not working and I don't use anything, nothing at all, no texture, no visual mod, nothing just bleach and fabric api nothing else and it just doesn't work anymore when I stay on FreeCam and I see on the walls the ores really appear the problem is that when I'm normal the normal blocks don't disappear and stay only in FreeCam or crossing the blocks works

**Comment by BleachDev** [comment]
Sodium issue
