### ISSUE TITLE
[Bug] Fortnite crash part 2

### ISSUE THREAD

**Issue by RedCarlos26** [BleachDrinker420/BleachHack#438]
Happens in 1.18 and 1.17. Crashes when placing blocks (scaffold for example)

[latest.log](https://github.com/BleachDrinker420/BleachHack/files/8150230/latest.log)

**Comment by BleachDev** [comment]
fixed in https://github.com/BleachDrinker420/BleachHack/commit/a4d8e2812d23b9dcd2fd76591d3de4672b394586

**Comment by RedCarlos26** [comment]
Hell yea thanks bleach
