### ISSUE TITLE
Bleach hack Detected by Windows Defender (just downloaded newest release from website)

### ISSUE THREAD

**Issue by linuzzx** [BleachDrinker420/BleachHack#451]
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aAndroidOS%2fMultiverze&threatid=2147785333

**Comment by linuzzx** [comment]
https://www.virustotal.com/gui/file/ad4cacf098f462f1cc4426641c37d6fcfcc123b79917f73dfb20cdb84372d2fd/detection

**Comment by sudofox** [comment]
Out of curiosity, what happens if you run the older version through virustotal? eg v1.2.5

Sort of related, but I remember this thread from Alexander of Wurst:

https://twitter.com/Wurst_Imperium/status/1229370457838755840

Renaming the method names fixed it for him

https://github.com/Wurst-Imperium/Wurst7/commit/3a5076b43960b74185265723f835e0c29db1243e

**Comment by BleachDev** [comment]
![disintegrate](https://user-images.githubusercontent.com/36450388/159548562-0c87910a-faa4-452b-aab6-7ce4153f358a.gif)

**Comment by BleachDev** [comment]
I replaced the release jars to maybe fix it but its probably the Discord IPC library thats causing it because it uses some weird pipe files to access discord

1.2.4 and earlier doesn't trigger it because they use a different rpc library

**Comment by YurniUwU** [comment]
Id also like to add that it spams the absolute living hell out of the latest.log
![Got it up to a damn gigabyte](https://user-images.githubusercontent.com/93057076/160320574-144681a3-b10e-4e79-ab5b-ebcde8669e65.png)

**Comment by linuzzx** [comment]
still flagged for me

**Comment by linuzzx** [comment]
Until including [BleachHack-1.2.5](https://github.com/BleachDrinker420/BleachHack/releases/tag/1.2.5) it works fine

**Comment by lele92007** [comment]
meteor's ipc isn't flagged
you could try using it instead

**Comment by BleachDev** [comment]
Don't think this happens anymore
