### ISSUE TITLE
[BUG] Notebot is broken as of 1.18.2 due to UseItemOnPacket

### ISSUE THREAD

**Issue by SolsticeSpectrum** [BleachDrinker420/BleachHack#452]
There is just bunch of spam in the log saying:
`[23:37:53] [Server thread/WARN]: Ignoring UseItemOnPacket from YourDoom: Location (186.97627587224568, -58.0, 257.0404752228146) too far away from hit block class_2338{x=185, y=-59, z=255}.`

**Comment by BleachDev** [comment]
FIxed in https://github.com/BleachDrinker420/BleachHack/commit/938c265eaa46c73620dee6ee71d0d64d3eba87d3
