### ISSUE TITLE
[Suggestion] No Break Delay 

### ISSUE THREAD

**Issue by Ivans-s** [BleachDrinker420/BleachHack#461]
I would like to suggest a module I found in meteor client called **"No Break Delay"**

What it does is completely remove the delay between breaking blocks.
Since this is hard to detect for most anticheats it bypasses almost every 1.18 paid/free anticheats.

**Source -** 

https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/meteordevelopment/meteorclient/systems/modules/player/NoBreakDelay.java

**Comment by BleachDev** [comment]
Already an option under speedmine
