### ISSUE TITLE
Can't join the server when I use bleachhack

### ISSUE THREAD

**Issue by Inz4n1ty** [BleachDrinker420/BleachHack#470]
Hello, I have the problem with joining servers when I use bleachhack. When i was trying to connect to the server, there always was an error "Disconnected". So, may be it rejects to work with other cheat clients and mods(Currently I am using meteor + seedcracker) And decided to put away them from the mods' folder. Well it didn't work.

P.S I play minecraft 1.18.2

**Comment by Inz4n1ty** [comment]
Dont need help

**Comment by Inz4n1ty** [comment]
1

**Comment by helloalp** [comment]
i met the totally same problem.When i'm using bleach hack to join a anarchy server with using of meteor,it kept showing "**joining the world**"
