### ISSUE TITLE
Suggestion: Only fully grown crops for Nuker

### ISSUE THREAD

**Issue by Bedo05** [BleachDrinker420/BleachHack#493]
Make it so that you can toggle only fully grown crops like nether wart, wheat, and carrots for nuker.  This mod would be so much more useful if you could do that

**Comment by Bedo05** [comment]
Breaking baby crops destorys farms and farms could be fully afkable and you would farm more effectively when using the replenish enchantment

**Comment by BleachDev** [comment]
Use AutoFarm with crops enabled instead
