### ISSUE TITLE
[Suggestion] Add Ignore-Above toggle option to Notebot

### ISSUE THREAD

**Issue by ghost** [BleachDrinker420/BleachHack#499]
Bleachhack ignores noteblocks that have been disabled by a block on top of that noteblock because thats normally the vanilla behavior.

Since there are Server types (Purpur) that allow disabling that vanilla behavior for more noteblock functionality though, it would make sense to add that option.

This way, more compact noteblock booths could be used on servers that allow it.

**Comment by ghost** [comment]
@BleachDev One year old issue

**Comment by Meesterbouwer123** [comment]
Is it one year since bleachhack got discontinued?
