### ISSUE TITLE
add nbs file support

### ISSUE THREAD

**Issue by ayunami2000** [BleachDrinker420/BleachHack#55]
plEASE
i NEED nbs file support

one big reason is because if i just use wwe and bleachhack at the same time theres some considerable client-side/server-side lag even on a singleplayer world which detunes the songs. Additionally having a tick-based song file may be worse than a millisecond-based song (not 100% confirmed tho)

**Comment by bossdragon** [comment]
use a different tuner like batch 5 if you have lag

**Comment by Godeps2891** [comment]
@BleachDrinker420 please add!!!!!!!!!

**Comment by BleachDev** [comment]
Added
