### ISSUE TITLE
suggestions from other clients

### ISSUE THREAD

**Issue by ayunami2000** [BleachDrinker420/BleachHack#57]
rn i use wurst, wwe, and bleachhack all at once, but i would like to only use one client.
personally in a hacked client i would like:

- wurst's boatfly (it sometimes works on other entities too) (urs doesnt let all entites fly, wurst's works better for flying and also has a slow fall, which u should add to ur entityride as an option for slow fall)
- wwe's entityride's "ride without saddle"
- wurst's .give command
- wurst's .modify command
- wurst's .viewnbt command
- wurst's .rename command
- wurst's .copyitem command (also add offhand support since wurst doesnt have that yet for some reason)
- wurst's .enchant command
- wurst's .potion command
- wurst's .repair command
- antiknockback, nopush, noslowdown, antiblind, nofall, etc. (wurst has these so prob just use wurst's ones since it's also updated to 1.16.1 and open source & wwe isn't) (idk which ones u already have)
- autobuild? (maybe like wurst's autobuild but it supports schematics, or like some client side worldedit clone maybe? clientside worldedit would actually be epic tbh)
- wurst's "last server" button
- wwe's click teleport

ik this is a lot but itll make this client really good, especially the client side worldedit for autobuilding which would be unique _and_ really cool

**Comment by lasnikprogram** [comment]
I already programmed a lot of stuff with the wurst client. So I am really familiar with all features and most of the code.

As soon as I find time I am going to make your request possible. This should be done in 1 month cause I am busy lol

**Comment by ayunami2000** [comment]
epic

**Comment by lasnikprogram** [comment]
By the way: I already have a way nicer entity/boat fly hack. I am going to transfer it really soon

**Comment by BleachDrinker420** [comment]
i already have .give, .enchant, ride without saddle, .viewnbt and .rename
aso .modify? if thats to edit neb on a item

**Comment by BleachDrinker420** [comment]
and i'm working on a new boatfly, that would take like 2 minutes

**Comment by BleachDrinker420** [comment]
and also antiknockback, noslowdown and nofall

**Comment by BleachDrinker420** [comment]
so what i don't have:
* .copyitem
* .potion
* .repair
* nopush, antiblind
* autobuild (no)
*last server button
* click teleport

**Comment by ayunami2000** [comment]
yes .modify is to edit nbt.

- .copyitem copies another user's item like .copyitem <hand|head|chest|feet|legs|offhand>
- .potion allows u to edit the held potion (basically an organized nbt editor for potions)
- .repair restores held item durability
- click teleport, at least in wwe, highlights the block that ur looking at and when you right click you teleport there. I use it to phase through walls sometimes when i spam it enough (its really difficult tho).
- nopush is just block entities/players from pushing u
- antiblind obv blocks blindness effect
- autobuild is just like schematica/litematica but simpler and a client side worldedit method of doing so would make it really easy to use

**Comment by ayunami2000** [comment]
oh and one suggestion that doesnt exist yet: maybe a way to steal from invsee? like invsee lets u see other people's inventories (the command does) but you cant take from them. maybe a way to press a key while hovering over the item and it saves it off to the side of the inventory where you can later click it and the client will create the item in your inventory? kinda like from this mod Roughly Enough Items:
![image](https://user-images.githubusercontent.com/24785136/87230891-c49bda80-c380-11ea-9d99-1b3946f44d81.png) but built into the client instead of a separate mod?

**Comment by ayunami2000** [comment]
oh and i forgot about wurst's infinichat which is a must for using with the give command
