### ISSUE TITLE
suggestion:auto gapple

### ISSUE THREAD

**Issue by TheRealDunk69** [BleachDrinker420/BleachHack#66]
automatically eats a gap when at low health

**Comment by 22s** [comment]
to add onto this an autoeat thats compatible w/ fabritone would be nice along with interchangeable settings to eat at low health or low hunger

**Comment by SukkaW** [comment]
@BleachDrinker420

Is the feature being working on? I see some fork version of the bleachhack has the feature implemented: https://github.com/HerraVp/BleachHack-VpEdition/blob/master/BleachHack-Fabric-1.17/src/main/java/bleach/hack/module/mods/AutoEat.java

**Comment by BleachDrinker420** [comment]
Added in https://github.com/BleachDrinker420/BleachHack/commit/106d9eb13329a1013f27988df90596397b26fea1
