### ISSUE TITLE
bug: storage esp is jittering

### ISSUE THREAD

**Issue by lawrencfgsdfg** [BleachDrinker420/BleachHack#86]
on bleachhack 13.1 on 1.15

**Comment by BleachDrinker420** [comment]
its due to floating precision, it gets worse it further out you go from spawn, not really a lot i can do about it tho

**Comment by TheAirBlow** [comment]
I think make it double

**Comment by lasnikprogram** [comment]
This is fixed btw @BleachDrinker420

**Comment by BleachDrinker420** [comment]
ok
